browser=chrome
url=https://www.poscentral.biz/	  
 
Login--- 
useremail=shubhamtest333@gmail.com
invalidemail=invalidemail@invalid.com
emailspace=shubhamtest333@gmail.com
c_password=Bwit@123
w_password=Bwit@12345

Registraion---
Ruseremail=test555@gmail.com
usermobile=423456524
userfirstname=Rahul
userlastname=Kumar
useraddress=Delhi 6
usercitysuburb=new Delhi
userzipcode=4321
usercountry=Australia
userstate=Queensland

ConatctUsForm---
contactfirstname=Rahul
contactlastname=Kumar
contactcompanyname=Broadway Infotech Pvt Ltd
contactemail=rahultest123@gmail.com
contactphone=423456524
contactsubject=Test Contact Us Form
contactmessage=This is a test message for contact us form. Please ignore this message.

SearchProduct---
validproductname=POS Systems
exactproductname=ELO X-SERIES 20-INCH WW CORE I5 4GB RAM 128SSD WIN 7 TOUCHPRO
skunumber=SSSSS17726_2
partialproductname=Lapt
brandname=Microsoft
lowercaseproductname=dell multimedia keyboard
uppercaseproductname=DELL MULTIMEDIA KEYBOARD
mixcaseproductname=dymo LABELwriter 550 FOOD service
leadingspaceproductname=       dymo LABELwriter 550 FOOD service
trailingspaceproductname=dymo LABELwriter 550 FOOD service       
mixleadingtrailingspaceproductname=       dymo LABELwriter 550 FOOD service            
specialcharacterproductname=Spacepole X-Frame, Black, For Element He10-W+ + SPACEPOLE SAFEGUARD DURATILT & POLE BLK
discontinuedproductname=Datalogic Magellan 3200VSi Vertical Scanner, 1D, EAS Antenna & RS232 interface Cable
discontinuedproductsku=DLM3200V1E-R  
invalidproductname=Invalid Product Name

CartPage---
promocode=TestPromo

CardDetails---
cardnumber=4242424242424200
cvv=123
expiry=1227
cardholdername=TEST CARD 












